# Generated by Django 4.2.26 on 2025-12-10 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, help_text='Users who follow this user', related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
